name: Models tests

on: push

jobs:
  job1:
    name: model-testin
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Installing pytest
      run: |
        python -m pip install -r requirements.txt
    - name: Run language tests
      run: | 
        pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}